/**
 * Enum containing turn states
 */
export enum TurnState {
  NEW,
  DISPLAY_TEAM_TAKING_TURN,
  DISPLAY_DIFFICULTY_SELECTION,
  DISPLAY_CARDS,
  DISPLAY_TURN_EVALUATION,
  DISPLAY_SCORE_OVERVIEW,
}
