name: Build and Deploy to Firebase
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Clean
        run: |
          rm -rf ./dist/*
          rm -rf ./reports/*
          rm -rf ./coverage/*
          mkdir -p ./reports
      - name: Build Angular
        run: |
          cp ./src/favicon-s4f.ico ./src/favicon.ico
          cp ./src/manifest-s4f.webmanifest ./src/manifest.webmanifest
          npm install
          npm run build-s4f-prod -- --base-href 'https://sciddle-s4f.web.app/'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project sciddle-riddle --only hosting:sciddle-s4f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
