name: Release app for https://sciddle.de
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Clean
        run: |
          rm -rf ./dist/*
          rm -rf ./reports/*
          rm -rf ./coverage/*
          mkdir -p ./reports
      - name: Build Angular
        run: |
          npm install
          npm run build-regular-prod -- --base-href 'https://sciddle.de/'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project sciddle-riddle --only hosting:sciddle-riddle
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
